### ISSUE TITLE
Few question regarding the Centris API

### ISSUE THREAD

**Issue by ikus060** [npow/centris#21]
Hi,

I'm trying to integrate with Centris in a similar ways to you and I' wondering how you manage to get your hand on this API. Did you contact centris to give you documentation or something ? Help would be appreciate if you can point me into the right direction to know what are the API provided by centris.

Thanks

**Comment by npow** [comment]
No, there isn't an API for Centris (not that I'm aware of anyway).

**Comment by voyera** [comment]
If you're looking to use a Centris API I have made a tool that ingests their daily zip dumps and creates an API for you to use.

**Comment by AndrewMutation** [comment]
@voyera I would really like to know where to find those zips. 

I was asked to look at something while I have some time, not sure if its for a client. If it is, the api might be interesting too.

**Comment by ipodishima** [comment]
@voyera Would be interested too! I'm looking to do or use something which would list me the new properties fitting my criterias instead of doing it manually each day :D

**Comment by voyera** [comment]
Sorry about the delay guys. @AndrewMutation you have to provide centris with an agreement form between the realtor and you allowing you to get dumps of their centris data which is zipped in the forms of csv all within one zip file via FTP daily (very archaic.).

Unfortunately Centris is not really keen about sharing their data which is why this can be a pain to setup websites as per their specs to realtor clients. That's why I created tool that ingest those CSVs and allows me to poke at it via an API instead.

@ipodishima sorry for the bad news, I don't think my method would allow you to do what you want unfortunately!

**Comment by AndrewMutation** [comment]
Thanks for the reply,

I was hoping there was a way to get the data without having a realtor agreement.

In the end, it wasn't for a client, it was just an idea to simplify looking through the results that a realtor provided.

:)

I my personal use, I found the Centris site much harder use than Realtor.ca

**Comment by Momzweasley** [comment]
> If you're looking to use a Centris API I have made a tool that ingests their daily zip dumps and creates an API for you to use.

Hi, 
I would like to use that tool if you still have it @voyera .
Thanks

**Comment by voyera** [comment]
@Momzweasley  you can ping me at alexandre(dot)voyer(at)outlook.com  I could walk you through what I've done. Heads up, at this time I am not willing to provide it for free.

The (basic) API documentation is found here (French only, but you should get the idea with the API calls): http://documentation.servicescourtage.com/

**Comment by hasbrak** [comment]
Hello @voyera, 
I'm interested to use your API to build call on Matrix. I've already try with postman and it's working great. But I would like have more information. 
How can I contact you ? I'm physically in Montreal. Je parle français aussi

Thanks

**Comment by avoyer-fuze** [comment]
@hasbrak  I'm in Ottawa, you can ping me at my email to get discussion going. :) Je parle francais egalement.

**Comment by jsamouh** [comment]
Hi @avoyer-fuze @voyera  ? I sent you an email ;-)

**Comment by voyera** [comment]
I saw, will reply this evening. :)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dsignica** [comment]
> @hasbrak I'm in Ottawa, you can ping me at my email to get discussion going. :) Je parle francais egalement.
I'm interested to use your API. I  send you an email.

**Comment by dsignica** [comment]
> @hasbrak I'm in Ottawa, you can ping me at my email to get discussion going. :) Je parle francais egalement.

I'm interested to use your API. I send you an email.

**Comment by jeff06** [comment]
I know im a bit late, but ive made a C# api for centris. https://github.com/jeff06/CentrisApiHomeBrew

Its in C#. It work quite well.

**Comment by Teiwaz83** [comment]
> you have to provide centris with an agreement form between the realtor and you allowing you to get dumps of their centris data which is zipped in the forms of csv all within one zip file via FTP daily (very archaic.).

@voyera it's been a couple years - do you remember any details about this process? Like a name or anything like that? I called Centris support and they denied any knowledge of any such system existing.

**Comment by h3** [comment]
@Teiwaz83 I interfaced the system @voyera is referring to around 2012 with Python for a couple of sites .. pretty sure it has been retired since then (I hope so!).

We had to fill a "Demande de transfert de données" form on behalf of our client which required an brokerage agency number and broker license number otherwise they don't give access to the data.

Then you had to provide Centris a FTP server where they would dump daily a zip file containing CSV listings. They would send field changes (their version of database migration) via email with short notice. The hole thing was an abomination to maintain.
 
The pricing was also why we stop offering it to our client .. the billing couldn't be passed to our client directly (the brokerage agencies). Centris insisted on charging the _development_ agency (us) on a per listing basis. The first 250 listing were free, but as we accumulated customers we get more listing to synchronize and start getting charged for daily transfer of all of our customer combined. Their grand plan was that the development agency would then charge their customers a monthly fee, but they always all refused.

I still have all the documentation, but it came with an NDA so .. Some things are better off dead anyway :)

**Comment by hasbrak** [comment]
A Python script using [scrappy ](https://scrapy.org/) is quite easy to get data,

**Comment by voyera** [comment]
Well put @h3 ! That FTP craziness was a pain in the neck.

@hasbrak definitely, the issue is it's missing some important fields. I can't recall from the top of my head unfortunately since I haven't played with Centris for many years now but you'll understand when you compare it with the raw data that centris has behind the scene in the realtor's portal.

**Comment by pixel-hub** [comment]
Anyone tried https://syncbroker.com ? Is there anyway to reproduce what they have?
